import Navbar from "@/components/Navbar";
import "./globals.css";
import SocialSideBar from "@/components/SocialSideBar";
import { League_Spartan } from "next/font/google";
export const metadata = {
  title: "Arlie Torres",
  description: "Generated by create next app",
};
const league = League_Spartan({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={league.className} lang="en">
      <body id="content">
        <main className="flex relative ">
          <Navbar />
          <main className="flex-1  relative">
            {children}
            <aside className="stickySidebar  ">
              <SocialSideBar />
            </aside>
          </main>
        </main>
      </body>
    </html>
  );
}
