import Navbar from "@/components/Navbar";
import "./globals.css";
import SocialSideBar from "@/components/SocialSideBar";
import { League_Spartan } from "next/font/google";
export const metadata = {
  title: "Arlie Torres",
  description: "Generated by create next app",
};
const league = League_Spartan({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  /* id = "content"; */
  return (
    <html className={league.className} lang="en">
      <body className="relative">
        <Navbar />
        <main className="relative ">
          {children}
          <SocialSideBar />
        </main>
      </body>
    </html>
  );
}
